version: '3.7'
services:
  postgres-docker-container:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_DB=currency
      - POSTGRES_PASSWORD=teste
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    networks:
      spring-cloud-network:
        aliases: 
          - postgres-docker-container
  spring-boot-docker-container:
    build: .
    depends_on:
      - postgres-docker-container
    links:
      - postgres-docker-container:postgres-docker-container
    ports:
      - 8080:8080
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD","http://localhost:8080/"]
    restart: on-failure:5 
    networks:
      spring-cloud-network:
        aliases: 
          - spring-boot-docker-container
networks:
    spring-cloud-network: