name: DEVELOP CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]


jobs:
  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify 
      - name: Create build path staging
        run: mkdir staging && cp target/*.jar staging
      - name: Upload math result for job
        uses: actions/upload-artifact@v1
        with:
          name: currency_converter_develop
          path: staging


      
