# This is a basic workflow to help you get started with Actions

name: CI FOR DEV

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ homolog ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a one-line script   
        uses: actions/setup-java@v1
        with: 
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore: ${{ runner.os }}-m2
          
          
      # Runs a single command using the runners shell
      - name: Build
        run: mvn -B package --file pom.xml
      - name: Create build path staging
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v1
        with:
          name: currency_converter
          path: staging
