name: GitHub-Actions Example-PRD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build
      run: mvn -B package --file pom.xml
    - name: Maven clean Package
      run: mvn -B clean package -DskipTests
    - name: Tests
      run: mvn -B clean verify
    - name: Creating artifact
      run: mkdir production && cp target/*.jar production
    - name: Upload Artifact
      uses: actions/upload-artifact@v1     
      with:
        name: currency-converter-project
        path: production
    - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: currency-converter-project
        run: heroku plugins:install java && heroku create --no-remote && heroku deploy:jar staging/currency-0.0.1-SNAPSHOT.jar --app currency-converter-project